default: &default
  adapter: postgresql

development:
  <<: *default
  database: ghostship_development

test:
  <<: *default
  database: ghostship_test

production:
  <<: *default
  database: ghostship_production
